### ISSUE TITLE
Information Button on Cover Page/Update Name

### ISSUE THREAD

**Issue by jedi3r4** [Suggester-Bot/Documentation#40]
A button named the same as the Suggester Docs (or the below names) that Directs to the Suggester Docs on Cover Page along with changing the Suggester Docs Page to being named Bot Introduction or Suggester Introduction (to make it clearer what that page is) needs to be updated in all these branches:

- [ ] translation-template

- [ ] french

- [ ] spanish

- [ ] dutch

**Description:**
Add a description here if needed

(Both me and Suspense talked about this)

**Comment by KarateWumpus** [comment]
For now i will keep the sidebar link as suggester docs
